# Generated by Django 2.2.5 on 2019-09-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('thumbs_up', models.IntegerField(default=0)),
                ('thumbs_down', models.IntegerField(default=0)),
                ('theme', models.CharField(choices=[('Music', 'Music'), ('Entertainment', 'Entertainment'), ('Education', 'Education'), ('Kitties', 'Kitties'), ('Doggos', 'Doggos')], max_length=100)),
            ],
        ),
    ]
